#!/usr/bin/env python3

# Copyright (c) 2020 - for information on the respective copyright owner
# see the NOTICE file and/or the repository
# <https://github.com/boschresearch/amira-blender-rendering>.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""This script runs the implemented tests in ./tests/
Since we need to invoke blender and bpy, the scripts is used to run the tests by
calling blender with the run_tests command line interface.
This wrapper around blender is not essential, yet convenient to run tests by e.g.

    ./scripts/run_tests --abr-path ~/amira_blender_rendering
"""

import os
import subprocess
from argparse import ArgumentParser

    
def parse_arguments():
    parser = ArgumentParser()
    parser.add_argument('--abr-path', type=str, default=None, dest='abr_path',
                        help='Path to amira_blender_rendering root directory')
    
    args = parser.parse_args()
    return args


if __name__ == "__main__":
    
    args = parse_arguments()
    
    # build command and arguments to run
    cmd = ['blender', '-b', '-P', os.path.join(os.getcwd(), 'tests', 'run_tests.py'), '--']
    if args.abr_path is not None:
        cmd += ['--abr-path', args.abr_path]
 
    subprocess.run(cmd)
