# Workflow to build and publish latest documentation from abr/feature/build-documentation

name: build ABR documentation
on: 
  push:
    branches:
      - master
      
defaults:
  run:
    shell: bash

jobs:
  build-and-publish:
    runs-on: ubuntu-20.04
    container: python:3.8
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2  # checkout code
      
      - name: Setup project
        run: pip install -r requirements.txt  # install additional requirements (among which sphinx theme)
      
      - name: Build-Docs
        run: mkdocs build
      
      - name: Deploy Pages
        run: mkdocs gh-deploy --force
