# Workflow to build and publish latest documentation from abr/feature/build-documentation

name: build ABR documentation
on: 
  push:
    branches:
      - feature/actions
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # checkout code
      - run: python3 -m pip install -r requirements.txt
      - run: cd docs
      - run: make html && ls -la _build/
