# Workflow to build and publish latest documentation from abr/feature/build-documentation

name: build ABR documentation
on: 
  push:
    branches:
      - feature/abr-documentation
      
defaults:
  run:
    shell: bash

jobs:
  build-and-publish:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2  # checkout code

      - name: Install sphinx
        run: pip install -U Sphinx
      
      - name: Install requirements
        run: pip install -r requirements.txt  # install additional requirements (among which sphinx theme)
      
      - name: Build documentation
        run:  export PATH=$PATH:/home/$USER/.local/bin && cd docs && make html  # build documentation
      
      - name: Deploy to Pages
        run: echo "Fake deploy"
