# Workflow to build and publish latest documentation from abr/feature/build-documentation

name: build ABR documentation
on: 
  push:
    branches:
      - feature/abr-documentation
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # checkout code
      - run: which python
      - run: python --version
      - run: which pip
      - run: pip --version
      - run: python3 -m pip --version
      - run: python3 -m pip install Sphinx  # install sphinx to compile doc
      - run: python3 -m pip install -r requirements.txt  # install additional requirements (among which sphinx theme)
      - run: cd docs && make html  # build documentation
      - run: ls -la
