# this is a first dummy workflow file for playing around with GH actions

name: dummy-workflow-actions
on: push
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello-world"

